/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.awt.TextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java .awt.TextArea;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
/**
 *
 * @author User
 */
public class salary extends Find {

    /**
     * Creates new form salary
     */
    public salary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        selected = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        condition = new javax.swing.JTextField();
        select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(828, 770));

        jButton10.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Capture.PNG")); // NOI18N
        jButton10.setText("Calculate");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Select what?");

        selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Condition Select");

        select.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        select.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\se.PNG")); // NOI18N
        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selected, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selected, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        Statement stmt,st,s,paid;

        try{
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/human-resource";
            //database schema: eng

            Connection con = DriverManager.getConnection( url,"root", "16121990" );

            ResultSet qs,es,ws,ps,rs;

            stmt = con.createStatement();
            st = con.createStatement();
             s = con.createStatement();
             paid = con.createStatement();
            String Result="",count="",counte="",countee="";
            //String adrs=jComboBox36.getSelectedItem().toString();
            String id,department="",working="";
            id=jTextField2.getText();
            //department=jTextField3.getText();
             //working=jTextField5.getText();
             ps = paid.executeQuery("select Wid from paid where Eid= '"+id+"'");
             int x=0;
             while(ps.next()){
                working+=ps.getObject(1).toString();//+rs.getObject(2).toString()+"\n ";//+rs.getObject(3).toString()+"\n";
                x++;
            }
            rs = paid.executeQuery("select Qid from paid where Eid= '"+id+"'");
             int z=0;
             while(rs.next()){
               department+=rs.getObject(1).toString();//+rs.getObject(2).toString()+"\n ";//+rs.getObject(3).toString()+"\n";
                z++;
            }
       
            qs = stmt.executeQuery("select University from qulification where Qid= '"+department+"'");
            es = st.executeQuery("select job from employee where Eid= '"+id+"'");
             ws = s.executeQuery("select startworking from workingdate where Wid= '"+working+"'");
         
        
            int i=0,j=0 ;

            while(qs.next()){
                count+=qs.getObject(1).toString();//+rs.getObject(2).toString()+"\n ";//+rs.getObject(3).toString()+"\n";
                i++;
            }
while(es.next()){
                counte+=es.getObject(1).toString();//+rs.getObject(2).toString()+"\n ";//+rs.getObject(3).toString()+"\n";
                j++;
            }
while(ws.next()){
                countee+=ws.getObject(1).toString();//+rs.getObject(2).toString()+"\n ";//+rs.getObject(3).toString()+"\n";
                i++;
            }
Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(countee); 
Calendar cal = Calendar.getInstance();
        cal.setTime(date1);
        int result = cal.get(Calendar.YEAR);
          
      DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
         Date today = new Date();
         Calendar cal1 = Calendar.getInstance();
        cal.setTime(today);
        int result1 = cal.get(Calendar.YEAR);
           


            int sal3=((result1-result)/2)*100;
            
            if (count.equalsIgnoreCase("dr") ){
                if(counte.equalsIgnoreCase("maneger")){
                  System.out.println(sal3);
                  st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+800+"','"+3000+"','"+(sal3+800+3000)+"')");}
                else
                 st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+0+"','"+3000+"','"+(sal3+3000)+"')");
            }
            else if (count.equalsIgnoreCase("master") ){
                if(counte.equalsIgnoreCase("maneger")){
                  System.out.println(sal3);
                  st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+700+"','"+2700+"','"+(sal3+800+2700)+"')");}
                else
                 st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+0+"','"+2700+"','"+(sal3+2700)+"')");
            }
                else if (count.equalsIgnoreCase("BA") ){
                if(counte.equalsIgnoreCase("maneger")){
                  System.out.println(sal3);
                  st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+500+"','"+2500+"','"+(sal3+800+2500)+"')");}
                else
                 st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+0+"','"+2500+"','"+(sal3+2500)+"')");
            }
                else if(count.equalsIgnoreCase("diploma")){
                if(counte.equalsIgnoreCase("maneger")){
                  System.out.println(sal3);
                  st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+200+"','"+2000+"','"+(sal3+200+2000)+"')");}
                else
                 st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+0+"','"+2000+"','"+(sal3+2000)+"')");
                }
                else{
                    if(counte.equalsIgnoreCase("maneger")){
                  System.out.println(sal3);
                  st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+200+"','"+1700+"','"+(sal3+200+1700)+"')");}
                else
                 st.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" +" VALUES ('"+sal3+"','"+0+"','"+1700+"','"+(sal3+1700)+"')");
                    
                }
            //jTextArea1.append(Result);

            con.close();
        }

        catch(Exception ee){
            System.out.println(ee.toString());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void selectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectedActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed

        Statement stmt;

        try{
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/human-resource";
            //database schema: human-resource

            Connection con = DriverManager.getConnection( url,"root", "16121990" );// connect to sql

            ResultSet query_select;

            stmt = con.createStatement();

            //String adrs=jComboBox36.getSelectedItem().toString();

            String selection,select_condition;
            selection=selected.getText();
            select_condition=condition.getText();

            query_select = stmt.executeQuery("select "+selection+" from salary where "+select_condition+"");
            ResultSetMetaData rsm = query_select.getMetaData();

            String Result="";

            String count="";
            while(query_select.next()){
                for(int j=1;j<rsm.getColumnCount()+1;j++){
                    count+=query_select.getObject(j).toString()+" - "+"\n";//+rs.getObject(2).toString()+"\n ";//+rs.getObject(3).toString()+"\n";

                }

                Result= count+"\n==========================\n";//}
            //TextArea JTextArea1=new TextArea();
            jTextArea1.append(Result);
        }

        con.close();

        }

        catch(Exception ee){
            System.out.println(ee.toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_selectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField condition;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton select;
    private javax.swing.JTextField selected;
    // End of variables declaration//GEN-END:variables
}
