/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author User
 */
public class Salary extends HumanResource {

    /**
     * Creates new form salary
     */
    public Salary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculate = new javax.swing.JButton();
        id1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        select1 = new javax.swing.JLabel();
        selectWhat = new javax.swing.JTextField();
        condition1 = new javax.swing.JLabel();
        condition = new javax.swing.JTextField();
        select = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(831, 773));

        calculate.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        calculate.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Capture.PNG")); // NOI18N
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        id1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id1.setText("Employee ID");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        select1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        select1.setText("Select what?");

        selectWhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectWhatActionPerformed(evt);
            }
        });

        condition1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        condition1.setText("Condition Select");

        select.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        select.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\se.PNG")); // NOI18N
        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        jScrollPane2.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(condition1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(select1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(condition1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(condition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:

        calculatesalary();
    }//GEN-LAST:event_calculateActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void selectWhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectWhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectWhatActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed

        selectSalary();

    }//GEN-LAST:event_selectActionPerformed

    public void calculatesalary() {

        Statement stmt, stmt1, stmt2, stmt3;// define statment to make connect to sql

        try {
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/human-resource";
            // to connect to my sql
            //database schema name: human-resource

            Connection con = DriverManager.getConnection(url, "root", "16121990");
            // put user name and password
            //username : root
            //password : 16121990

            stmt = con.createStatement();// start connection
            stmt1 = con.createStatement();// start connection
            stmt2 = con.createStatement();// start connection
            stmt3 = con.createStatement();// start connection

            String employeeID;

            employeeID = id.getText();// get employee id from text field

            ResultSet workingID;// define the result set of a database query
            workingID = stmt3.executeQuery("select Wid from paid where Eid= '" + employeeID + "'"); // get working id from paid table

            // to get working name
            String working = "";
            while (workingID.next()) {
                working += workingID.getObject(1).toString();

            }

            ResultSet qulificationID;// define the result set of a database query

            qulificationID = stmt3.executeQuery("select Qid from paid where Eid= '" + employeeID + "'");// get qulification id from paid table

            String department = "";
            //to get department name
            while (qulificationID.next()) {
                department += qulificationID.getObject(1).toString();

            }
            ResultSet qulificationResult, employeeResult, workingResult;// define the result set of a database query
            qulificationResult = stmt.executeQuery("select University from qulification where Qid= '" + department + "'");// get university degree from qulification table
            employeeResult = stmt1.executeQuery("select job from employee where Eid= '" + employeeID + "'");// get employee jobs
            workingResult = stmt2.executeQuery("select startworking from workingdate where Wid= '" + working + "'");// get date from working date table

            String finalResultQulification = "", finaEmployeeResult = "", finalWorkingResult = "";
            //  to get fianl qulification result
            while (qulificationResult.next()) {
                finalResultQulification += qulificationResult.getObject(1).toString();
            }
            //  to get fianl employee result
            while (employeeResult.next()) {
                finaEmployeeResult += employeeResult.getObject(1).toString();

            }
            //  to get fianl working result
            while (workingResult.next()) {
                finalWorkingResult += workingResult.getObject(1).toString();

            }
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(finalWorkingResult); //to make the date of working as format like 1190-12-16
            Calendar cal = Calendar.getInstance();// define calender
            cal.setTime(date1);
            int workingDate = cal.get(Calendar.YEAR); // take only year of the date
            // these code to take the date of today
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date today = new Date();
            Calendar cal1 = Calendar.getInstance();
            cal.setTime(today);
            int today1 = cal.get(Calendar.YEAR);// take only years

            int insentive = ((today1 - workingDate) / 2) * 100;// salory according to start working date
            // if wmployee is doctor(BASIC SALARY 3000) and if its is amanger (BOUNS IS 800) ELSES NO BOUNS
            int totalSalary = 0;
            if (finalResultQulification.equalsIgnoreCase("dr")) {
                if (finaEmployeeResult.equalsIgnoreCase("maneger")) {
                    totalSalary = insentive + 800 + 3000;

                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 800 + "','" + 3000 + "','" + totalSalary + "')");
                } else {
                    totalSalary = insentive + 3000;
                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 0 + "','" + 3000 + "','" + totalSalary + "')");
                }
            } // if employee is master(BASIC SALARY 2700) and if its is amanger (BOUNS IS 700) ELSES NO BOUNS
            else if (finalResultQulification.equalsIgnoreCase("master")) {
                if (finaEmployeeResult.equalsIgnoreCase("maneger")) {
                    totalSalary = insentive + 800 + 2700;

                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 700 + "','" + 2700 + "','" + totalSalary + "')");
                } else {
                    totalSalary = insentive + 2700;
                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 0 + "','" + 2700 + "','" + totalSalary + "')");
                }
            } // if employee is BA(BASIC SALARY 2500) and if its is amanger (BOUNS IS 500) ELSES NO BOUNS
            else if (finalResultQulification.equalsIgnoreCase("BA")) {
                if (finaEmployeeResult.equalsIgnoreCase("maneger")) {
                    totalSalary = insentive + 800 + 2500;

                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 500 + "','" + 2500 + "','" + totalSalary + "')");
                } else {
                    totalSalary = insentive + 2500;
                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 0 + "','" + 2500 + "','" + totalSalary + "')");
                }
            } // if employee is doctor(BASIC SALARY 2000) and if its is amanger (BOUNS IS 200) ELSES NO BOUNS
            else if (finalResultQulification.equalsIgnoreCase("diploma")) {
                if (finaEmployeeResult.equalsIgnoreCase("maneger")) {
                    totalSalary = insentive + 200 + 2000;

                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 200 + "','" + 2000 + "','" + totalSalary + "')");
                } else {
                    totalSalary = insentive + 2000;
                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 0 + "','" + 2000 + "','" + totalSalary + "')");
                }
            } // else(BASIC SALARY 1700) and if its is amanger (BOUNS IS 200) ELSES NO BOUNS
            else {
                if (finaEmployeeResult.equalsIgnoreCase("maneger")) {
                    totalSalary = insentive + 200 + 1700;

                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 200 + "','" + 1700 + "','" + totalSalary + "')");
                } else {
                    totalSalary = insentive + 1700;
                    stmt1.executeUpdate("INSERT INTO salary (Insentive,Bouns,basicSalary,Total)" + " VALUES ('" + insentive + "','" + 0 + "','" + 1700 + "','" + totalSalary + "')");
                }

            }
            result.append(Integer.toString(totalSalary));

            con.close();// close connection
        } catch (Exception ee) {
            System.out.println(ee.toString());
        }
    }

    public void selectSalary() {
        Statement stmt;// define statment to make connect to sql

        try {
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/human-resource";
            /// to connect to my sql
            //database schema name: human-resource

            Connection con = DriverManager.getConnection(url, "root", "16121990"); // put user name and password
            //username : root
            //password : 16121990

            stmt = con.createStatement();// start connection

            //String adrs=jComboBox36.getSelectedItem().toString();
            String selection, selectCondition;// define string selection and condition select
            selection = selectWhat.getText();//what coloums need select (name or id ir anther things )
            selectCondition = condition.getText();//what condition need
            ResultSet querySelect;// define the result set of a database query
            querySelect = stmt.executeQuery("select " + selection + " from salary where " + selectCondition + "");// condition to make slect
            ResultSetMetaData resultData = querySelect.getMetaData();//get metadata from the ResultSet object(queryselect).

            String selectionResult = "";
            // to check result at qulery
            while (querySelect.next()) {
                for (int coloums = 1; coloums < resultData.getColumnCount() + 1; coloums++) {// check coloum coloum
                    selectionResult += querySelect.getObject(coloums).toString() + " - " + "\n";//+rs.getObject(2).toString()+"\n ";//+rs.getObject(3).toString()+"\n";

                }
                String finalSelect = "";

                finalSelect = selectionResult + "\n==========================\n";//} // the final reault

                area.append(finalSelect);// the result appear in text arear
            }

            con.close();// close connection

        } catch (Exception ee) {
            System.out.println(ee.toString());
        }
        // TODO add your handling code here:

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField condition;
    private javax.swing.JLabel condition1;
    private javax.swing.JTextField id;
    private javax.swing.JLabel id1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea result;
    private javax.swing.JButton select;
    private javax.swing.JLabel select1;
    private javax.swing.JTextField selectWhat;
    // End of variables declaration//GEN-END:variables
}
